<div class="row">
<form action="search" method="post">
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
  <div class="col-xs-10 col-md-10 col-lg-10">
    <div class="input-group">
      <input type="text" class="form-control" name="term">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="submit" name="category" value="symptoms">Symptoms</button>
        <button class="btn btn-warning" type="submit" name="category" value="causes">Causes</button>
        <button class="btn btn-success" type="submit" name="category" value="solutions">Solutions</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
</form>
</div><!-- /.row -->
<div id="doggies-container">
    <?php foreach ($this->doggies as $doggy) : ?>
    <div class="row">
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
      <div class="col-xs-10 col-md-8 col-lg-8">
        <div class="row thumbnail">
<div class="col-xs-6 col-md-5 col-lg-4">
        <img src="<?php echo $doggy->getMedia()->getFile()->getSrc() ?>" alt="Thumb <?php echo $doggy->getCategory()->getName() ?>">
</div>
<div class="col-xs-6 col-md-7 col-lg-8">
          <div class="caption">
            <h3><?php echo $doggy->getTitle() ?></h3>
            <p><?php echo $doggy->getContent() ?></p>
            <p class="category">
            </p>
            <a href="<?php echo $this->url('dogtore_view', array('controller' => 'doggy', 'action' => 'view', 'id' => $doggy->getId()))?>">Read...</a>
            <p class="controls">
                <a href="<?php echo $this->url('blog', array('controller' => 'post', 'action' => 'edit', 'id' => $doggy->getId())) ?>">Edit</a>
            </p>
          </div>
</div>
        </div>
      </div>
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
    </div>
    <?php endforeach ?>
</div>
