<div class="row">
<?php
$form->setAttribute('action', $this->url('dogtore_search', array(), true));
$form->setAttribute('method', 'get');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?= $this->form()->openTag($form) ?>
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
  <div class="col-xs-10 col-md-10 col-lg-10">
    <div class="input-group">
      <?= $this->formElement($form->get('t')) ?>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><?= $this->translate('Any', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('symptom') ?>" type="submit" name="c" value="<?= $this->translate('symptom', 'dogtore')?>"><?= $this->translate('Symptoms', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('cause') ?>" type="submit" name="c" value="<?= $this->translate('cause', 'dogtore')?>"><?= $this->translate('Causes', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('solution') ?>" type="submit" name="c" value="<?= $this->translate('solution', 'dogtore')?>"><?php echo $this->translate('Solutions', 'dogtore')?></button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
<?= $this->form()->closeTag() ?>
</div><!-- /.row -->
<div id="doggies-container">
    <?php foreach ($doggies as $doggy) : ?>
    <div class="row">
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
      <div class="col-xs-10 col-md-8 col-lg-8">
        <div class="row thumbnail <?= $this->translate($doggy['lvl1_category_slug'], 'dogtore', 'en')?>">
<div class="col-xs-6 col-md-5 col-lg-4">
        <?php $imgPathParts = explode('/', $doggy['file_dirpath']);?>
        <?php $imgSrc = '/' . end($imgPathParts) . '/' . $doggy['file_basename'];?>
        <img src="<?php echo $imgSrc ?>" alt="Thumb <?php echo $doggy['lvl1_category_name'] ?>">
</div>
<div class="col-xs-6 col-md-7 col-lg-8">
        <span class="listing label label-<?= $this->cssClass($doggy['lvl1_category_slug'])?>"><?php echo $doggy['category_name'] ?></span>
        <div class="caption">
            <h3><?php echo $this->highlight($terms, $this->escapeHtml($doggy['post_title'])) ?></h3>
            <p><?php echo $this->nlToBr($this->highlight($terms, $this->escapeHtml($doggy['post_content']))) ?></p>
            <a href="<?php echo $this->url('dogtore_view', array('controller' => 'doggy', 'action' => 'view', 'id' => $doggy['post_id']))?>"><?php echo $this->translate('Read', 'dogtore')?>...</a>
            <p class="controls">
                <a href="<?php echo $this->url('blog', array('controller' => 'post', 'action' => 'edit', 'id' => $doggy['post_id']), true) ?>"><?php echo $this->translate('Edit', 'dogtore')?></a>
            </p>
          </div>
</div>
        </div>
      </div>
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
    </div>
    <?php endforeach ?>
</div>
