<?php 
$title = $this->translate('Edit your Profile');
$this->headTitle($title);
?>
<?php $this->notify(((isset($messages))? $messages : array())) ?>

<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
    <div class="col-sm-12 col-md-8 col-lg-6">
        <h1><?= $this->escapeHtml($title) ?></h1>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
</div>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
    <div class="col-sm-12 col-md-8 col-lg-6">
        <?php $this->formActionPrepare($form) ?>
        <?= $this->renderForm($form) ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
</div>
<?= $this->uploader() ?>
