<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-4 col-md-3 col-lg-3"><img src="<?php echo $media->getSrc()?>" alt="<?php echo $media->getAlt()?>"/></div>
    <div class="col-sm-6 col-md-5 col-lg-5">
<?php $patterns = array('firstname', 'surname')?>
<?php $replacements = array($profile->getFirstname(), $profile->getSurname())?>
    <h1><?php echo $this->patternTranslate($patterns, $replacements, "firstname surname's Profile", 'user') ?></h1>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-10 col-md-8 col-lg-8">
    <p><?php echo $profile->getContent()?></p>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
