<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-4 col-md-3 col-lg-3"><img src="<?php echo $media->getSrc()?>" alt="<?php echo $media->getAlt()?>"/></div>
    <div class="col-sm-6 col-md-5 col-lg-5">
    <h1><?php echo $profile->getFirstname()?> <?php echo $profile->getSurname()?>'s Profile</h1>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-10 col-md-8 col-lg-8">
    <p><?php echo $profile->getContent()?></p>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
