    <?php foreach ($profiles as $profile) : ?>
    <div class="row">
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
      <div class="col-xs-10 col-md-8 col-lg-8">
        <div class="row thumbnail">
<div class="col-xs-6 col-md-5 col-lg-4">
<?php
    $media = $profile->getMedia();
    $mediaMetadata = $media->getLocalizedMetadata($this->lang());
?>
            <img src="<?php echo $media->getSrc()?>" class="img-rounded img-responsive" alt="<?= ((null !== $mediaMetadata)? $mediaMetadata->getAlt() : '')?>"/>
</div>
<div class="col-xs-6 col-md-7 col-lg-8">
          <div class="caption">
          <h3><?php echo $profile->getFirstname() ?> <?php echo $profile->getSurname() ?></h3>
            <a href="<?php echo $this->url('profile_publicly_available', array('uniquename' => $profile->getUser()->getUniquename()), true)?>"><?php echo $this->translate('View')?>...</a>
          </div>
</div>
        </div>
      </div>
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
    </div>
    <?php endforeach ?>
