<?php
$this->notify(isset($messages)? $messages : array());
$title = 'Users';
$this->headTitle($title);
?>
<header class="row">
    <div class="col-xs-8 col-sm-4 col-md-4 col-4">
        <h3><?= $this->escapeHtml($this->translate($title)); ?></h3>
    </div>
    <div class="col-xs-0 col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-4">
    </div>
</header>

<?php $this->nonce()->setRouteName('dogtore_dog_noncedelete_route') ?>
<?php $masonryColumnWidth = 180 ?>
<?php if (empty($profiles)) : ?>
    <p><?= $this->translate('You have no dogs in your pack') ?></p>
<?php return ?>
<?php endif ?>

<div class="brick-wall row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <ul class="please_masonize_<?= $masonryColumnWidth ?>">
        <?php foreach($profiles as $profile) : ?>
            <?php
                $media = $profile->getMedia();
                $mediaMetadata = $media->getLocalizedMetadata($this->lang());
            ?>
            <li>
                <div>
                    <img src="<?php echo $media->getSrc()?>" class="img-rounded img-responsive" alt="<?= ((null !== $mediaMetadata)? $mediaMetadata->getAlt() : '')?>"/>
                  <div class="caption">
                    <h4><?php echo $profile->getFirstname() ?> <?php echo $profile->getSurname() ?></h4>
                    <p>
                        <a class="glyphicon glyphicon-eye-open" role="button" href="<?= $this->url('profile_publicly_available', array(
                            'uniquename' => $profile->getUser()->getUniquename()
                        ), true); ?>" title="<?= $this->translate('View') ?>"></a>
                    </p>
                 </div><!-- end caption -->
               </div><!-- end thumbnail -->
            </li>
        <?php endforeach ?>
        </ul>
    <?php require_once __DIR__ . '/../../../../Blog/view/partial/init_masonry.js.phtml' ?> 
    </div>
</div>
