<?php $this->notify(((isset($messages))? $messages : array())) ?>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-10 col-md-8 col-lg-8">
        <div class="row">
            <div class="col-sm-8 col-md-8 col-8">
                <?php $patterns = array('firstname', 'surname')?>
                <?php $replacements = array($profile->getFirstname(), $profile->getSurname())?>
                <h3><?= $this->patternTranslate($patterns, $replacements, "firstname surname's Profile") ?></h3>
            </div>
            <div class="col-sm-4 col-md-4 col-4">
                <p><a class="btn btn-success" href="<?php echo $this->url('profile_edit', array(
                    'controller' => 'profile', 
                    'action'=>'edit',
                    'uniquename'=> $user->getUniquename(),
                ), true);?>"><?php echo $this->translate('Edit Profile', 'user') ?></a></p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4">
                <img src="<?php echo $media->getSrc()?>" alt="<?php echo $media->getAlt()?>"/>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <ul>
                    <li><strong><?= $this->translate('Username')?></strong> : <?= $user->getUniquename()?></li>
                    <li><?= $this->userHasNDogsAndTheirNamesArePhrase($user, $referAsYou = true) ?></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
