<ul class="nav">
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php if( ! $page->hasPages()): ?>
            <li class="<?php if ($page->isActive()) echo 'active' ?>">
                <a class="nav-header" href="<?= $page->getHref() ?>">
                    <?= $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="<?= $page->getHref() ?>">
                    <?= $this->translate($page->getLabel()) ?>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                <?php foreach($page->getPages() as $child): ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                    <?php if (isset($child->divider) && 'above' === $child->divider): ?>
                        <li class="divider"></li>
                    <?php endif;?>
                    <?php if (isset($child->header)): ?>
                        <li class="nav-header"><?= $child->header?></li>
                    <?php endif;?>
                    <li>
                        <a href="<?= $child->getHref() ?>">
                            <?= $this->translate($child->getLabel()) ?>
                        </a>
                    </li>
                    <?php if (isset($child->divider) && 'below' === $child->divider): ?>
                        <li class="divider"></li>
                    <?php endif;?>
                <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
