<?php
$title = $this->translate('Login');
$this->headTitle($title);
?>
<?php $this->notify(((isset($messages))? $messages : array())) ?>
<div class="row">
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
    <div class="col-sm-10 col-md-4 col-lg-4">
        <h1 class="cancel-padding"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
    <div class="col-sm-10 col-md-4 col-lg-4">
        <?php $this->formActionPrepare($form) ?>
        <?= $this->renderForm($form) ?>
    </div>
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
</div>
