<?php
$title = $this->translate('Login');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-10 col-md-8 col-lg-8">
        <?= $this->notify(((isset($messages))? $messages : array())) ?>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
    <div class="col-sm-10 col-md-4 col-lg-4">
        <h1 class="cancel-padding"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
    <div class="col-sm-10 col-md-4 col-lg-4">
        <?php $this->formSameActionPrepare($form) ?>
        <?= $this->renderForm($form) ?>
    </div>
    <div class="col-sm-1 col-md-4 col-lg-4"></div>
</div>
