<?php
$this->formActionPrepare($form);
?>
<?php
$title = 'Register';
$this->headTitle($title);
?>
<?php $this->notify(((isset($messages))? $messages : array())) ?>

<div class="row">
    <div class="col-sm-1 col-md-3 col-lg-4"></div>
    <div class="col-sm-10 col-md-6 col-lg-4">
        <h1><?php echo $this->escapeHtml($title); ?></h1> 
    </div>
    <div class="col-sm-1 col-md-3 col-lg-4"></div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-3 col-lg-4"></div>
    <div class="col-sm-10 col-md-6 col-lg-4">
    <?= $this->renderForm($form) ?>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <p class="hint"><?= $this->translate('Already member?') ?>&nbsp;<a href="<?= $this->url('auth_login', array('action'=>'login'), true) ?>"><?= $this->translate('Login') ?></a></p>
                <p class="hint"><?= $this->translate('Forgot Password?') ?>&nbsp;<a href="<?= $this->url('auth_recoverpassword', array('action'=>'recoverpassword'), true) ?>"><?= $this->translate('Recover Password') ?></a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-1 col-md-3 col-lg-4"></div>
</div>
