<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$textDomain = prev($fileparts);
$route = array(
    'lang' => $this->lang(),
    'controller' => $controller,
    'action' => $action
);
if (null !== $entityId) {
    $route['id'] = $entityId;
}
$form->setAttribute('action', $this->url('blog',$route));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$elements = array();
foreach ($form->getFieldsets() as $fieldset) {
    $elements += $fieldset->getElements();
}
$elements +=$form->getElements();
?>
<?php
$title = ucfirst($this->translate($action, $textDomain)) . ' ' . ucfirst($this->translate($controller, $textDomain));
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>

<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
    <?php echo $this->form()->openTag($form)?>
        <?php foreach ($elements as $element) : ?>
            <?php $errors = $element->getMessages(); ?>
            <?php $hasErrors = !empty($errors) ?>
            <div class="form-group<?php echo (($hasErrors)? ' has-error' : '') ?>">
                <?php if (null !== $element->getLabel()) : ?>
                   <?php $element->setLabel($this->translate($element->getLabel(), $textDomain)) ?>
                   <?php echo $this->formLabel($element) ?>
                <?php endif ?>
                <?php echo $this->formElement($element) ?>
                <?php if ($hasErrors) :?>
                    <label class="control-label" for="<?php $element->getAttribute('name');?>"><?php echo $this->translate(current($errors), $textDomain)?></label>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php echo $this->form()->closeTag() ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>

<script type="text/javascript">
        $(function() {
            $('textarea[name="content"]').tinymce({
                    script_url : '/js/tiny_mce/tiny_mce.js',
                    theme : "advanced",
                    plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
                    // Theme options
                    theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,insertdate,inserttime,preview,template",
                    theme_advanced_resizing : true
            });
        });
</script>
