<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$textDomain = prev($fileparts);
$route = array(
    'action' => $action
);
if (isset($entityId) && null !== $entityId) {
    $route['id'] = $entityId;
}
$form->setAttribute('action', $this->url(null ,$route, true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php
$title = ucfirst($this->translate($action, $textDomain)) . ' ' . ucfirst($this->translate($controller, $textDomain));
$this->headTitle($title);
?>
<header class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</header>

<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
    <?php echo $this->form()->openTag($form)?>
        <?php foreach ($this->elementsFlatArray($form) as $element) : ?>
            <?php $errors = $element->getMessages(); ?>
            <?php $hasErrors = !empty($errors) ?>
            <div class="form-group<?php echo (($hasErrors)? ' has-error' : '') ?>">
                <?php if (null !== $element->getLabel()) : ?>
                   <?php $element->setLabel($this->translate($element->getLabel(), $textDomain)) ?>
                   <?php echo $this->formLabel($element) ?>
                <?php endif ?>
                <?php echo $this->formElement($element) ?>
                <?php if ($hasErrors) :?>
                    <label class="control-label" for="<?php $element->getAttribute('name');?>"><?php echo $this->translate(current($errors), $textDomain)?></label>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php echo $this->form()->closeTag() ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>
