    <?php foreach ($profiles as $profile) : ?>
    <div class="row">
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
      <div class="col-xs-10 col-md-8 col-lg-8">
        <div class="row thumbnail">
<div class="col-xs-6 col-md-5 col-lg-4">
        <img src="<?php echo $profile->getMedia()->getSrc() ?>" alt="<?php echo $profile->getMedia()->getAlt() ?>">
</div>
<div class="col-xs-6 col-md-7 col-lg-8">
          <div class="caption">
          <h3><?php echo $profile->getFirstname() ?> <?php echo $profile->getSurname() ?></h3>
            <p><?php echo $profile->getContent() ?></p>
            <a href="<?php echo $this->url('profile_publicly_available', array('uniquename' => $profile->getUser()->getUniquename()), true)?>"><?php echo $this->translate('Read', 'user')?>...</a>
          </div>
</div>
        </div>
      </div>
      <div class="col-xs-1 col-md-2 col-lg-2"></div>
    </div>
    <?php endforeach ?>
