<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$route = array(
    'controller' => $controller,
    'action' => $action
);
if (isset($entityId) && null !== $entityId) {
    $route['id'] = $entityId;
}
$form->setAttribute('action', $this->url('blog',$route));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$elements = array();
foreach ($form->getFieldsets() as $fieldset) {
    $elements += $fieldset->getElements();
}
$elements +=$form->getElements();
?>
<?php
$title = ucfirst($action) . ' ' . ucfirst($controller);
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>
<?php if (isset($messages) && !empty($messages)) : ?>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
    <?php foreach ($messages as $message) : ?>
        <?php $class = key($message); $message = current($message)?>
        <div class="alert alert-<?php echo $class ?>">
            <?php echo $message ?>
        </div><!-- end success -->
    <?php endforeach ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>
<?php endif ?>

<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
    <?php echo $this->form()->openTag($form)?>
        <?php foreach ($elements as $element) : ?>
            <?php $errors = $element->getMessages(); ?>
            <?php $hasErrors = !empty($errors) ?>
            <div class="form-group<?php echo (($hasErrors)? ' has-error' : '') ?>">
                <?php echo ((null !== $element->getLabel())? $this->formLabel($element) : '') ?>
                <?php echo $this->formElement($element) ?>
                <?php if ($hasErrors) :?>
                    <label class="control-label" for="<?php $element->getAttribute('name');?>"><?php echo current($errors);?></label>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    <?php echo $this->form()->closeTag() ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>

<script type="text/javascript">
        $(function() {
            $('textarea[name="content"]').tinymce({
                    script_url : '/js/tiny_mce/tiny_mce.js',
                    theme : "advanced",
                    plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
                    // Theme options
                    theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
                    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,insertdate,inserttime,preview,template",
                    theme_advanced_resizing : true
            });
        });
</script>
