<?php
$title = $this->translate('Categories', 'blog');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?php echo $this->url(
            'blog', 
            array(
                'controller' => 'category', 
                'action'=>'create',
            ),
            true
        )?>"><?php echo $this->translate('Add New Category', 'blog') ?></a></p>
    </div>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th><?php echo $this->translate('Category', 'blog')?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->renderTree($categories, 'flatArray') as $category) : ?>
	    <tr>
            <td style="padding-left:<?php echo ($category['lvl'] * 2) + 1?>em;"><?php echo $category['name'];?></td>
	        <td>
                <a href="<?php echo $this->url(
                    'blog', 
                    array(
                        'controller' => 'category', 
                        'action'=>'edit', 
                        'id' => $category['id']
                    ),
                    true
                ); ?>"><?php echo $this->translate('Edit', 'blog') ?></a>
	        </td>
	        <td>
                <a href="<?php echo $this->url(
                    'blog', 
                    array(
                        'controller' => 'category', 
                        'action'=>'delete', 
                        'id' => $category['id']
                    ),
                    true
                ); ?>" onclick="return confirm('Are you sure?')"><?php echo $this->translate('Delete', 'blog') ?></a>
	        </td>
	    </tr>
    <?php endforeach; ?>
    <?php if (empty($categories)) : ?>
	    <tr>
            <td><?php echo $this->translate('You have not added any category for the moment...', 'blog')?></td>
	    </tr>
    <?php endif ?>
</table>
