<?php
$title = 'Categories';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?php echo $this->url('blog', array(
            'controller' => 'category', 
            'action'=>'create',
        ));?>"><?php echo $this->translate('Add New Category', 'blog') ?></a></p>
    </div>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>Category</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($categories as $category) : ?>
	    <tr>
	        <td><?php echo $this->escapeHtml($category->getName());?></td>
	        <td>
                <a href="<?php echo $this->url('blog', array('controller' => 'category', 'action'=>'edit', 'id' => $category->getId())); ?>"><?php echo $this->translate('Edit', 'blog') ?></a>
	        </td>
	        <td>
                <a href="<?php echo $this->url('blog', array('controller' => 'category', 'action'=>'delete', 'id' => $category->getId())); ?>" onclick="return confirm('Are you sure?')"><?php echo $this->translate('Delete', 'blog') ?></a>
	        </td>
	    </tr>
    <?php endforeach; ?>
</table>
