<?php
$title = 'Files Library';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('blog', array(
    'controller' => 'file', 
    'action'=>'upload',
));?>">Add new File</a></p>
<table class="table table-bordered table-hover">
    <tr>
        <th>File</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($files as $file) : ?>
	    <tr>
	        <td><?php echo $this->escapeHtml($file->getName());?></td>
	        <td>
                <a href="<?php echo $this->url('blog', array(
                    'controller' => 'file', 
                    'action' => 'edit', 
                    'id' => $file->getId(),
                )); ?>">Edit</a>

	        </td>
	        <td>
                <a href="<?php echo $this->url('blog', array(
                    'controller' => 'file', 
                    'action' => 'delete',
                    'id' => $file->getId()
                )); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	    </tr>
    <?php endforeach; ?>
</table>
