<?php 
$title = $this->translate('Add a dog to your pack');
$this->headTitle($title);
?>
<?php $this->notify(((isset($messages))? $messages : array())) ?>

<header class="row">
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
    <div class="col-sm-12 col-md-8 col-lg-6">
        <h3><?= $this->escapeHtml($title) ?></h3>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
</header>
<?php $this->formActionPrepare($form) ?>
<?= $this->form()->openTag($form)?>
<div class="row">
    <div class="col-sm-0 col-md-1 col-lg-1"></div>
    <div class="col-sm-5 col-md-4 col-lg-4">
<?php
    $elements       = $this->elementsFlatArray($form);
    $restOfElements = array_diff_key($elements, array_flip(array('name', 'birthdate', 'gender', 'breed', 'color', 'weightkg', 'media',))); 
?>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['name']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-7 col-lg-8">
                <?= $this->renderElement($elements['birthdate']) ?>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4">
                <?= $this->renderElement($elements['gender']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['breed']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?= $this->renderElement($elements['color']) ?>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?= $this->renderElement($elements['weightkg']) ?>
            </div>
        </div>
        <?php foreach ($restOfElements as $element) : ?>
            <?= $this->renderElement($element) ?>
        <?php endforeach ?>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <div class="row media">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['media']) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>

<?= $this->uploader()?>

<?php require_once realpath(__DIR__ . '/../../partial') . '/init_modernizr_colpick.js.phtml'?>
<?php require_once realpath(__DIR__ . '/../../partial') . '/jquerydatepicker_modernizr.js.phtml'?>
