<?php 
$title = $this->translate('Add a dog to your pack');
$this->headTitle($title);
?>
<?php $this->notify(((isset($messages))? $messages : array())) ?>

<header class="row">
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
    <div class="col-sm-12 col-md-8 col-lg-6">
        <h3><?= $this->escapeHtml($title) ?></h3>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-3"></div>
</header>
<?php $this->formActionPrepare($form) ?>
<?= $this->form()->openTag($form)?>
<div class="row">
    <div class="col-sm-0 col-md-1 col-lg-1"></div>
    <div class="col-sm-5 col-md-4 col-lg-4">
<?php
    $elements       = $this->elementsFlatArray($form);
    $restOfElements = array_diff_key($elements, array_flip(array('name', 'birthdate', 'gender', 'breed', 'color', 'weightkg', 'media',))); 
?>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['name']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-7 col-lg-8">
                <?= $this->renderElement($elements['birthdate']) ?>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4">
                <?= $this->renderElement($elements['gender']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['breed']) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?= $this->renderElement($elements['color']) ?>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?= $this->renderElement($elements['weightkg']) ?>
            </div>
        </div>
        <?php foreach ($restOfElements as $element) : ?>
            <?= $this->renderElement($element) ?>
        <?php endforeach ?>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <div class="row media">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->renderElement($elements['media']) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>

<div class="row">
    <div class="col-sm-0 col-md-1 col-lg-1"></div>
    <div class="col-sm-5 col-md-4 col-lg-4"></div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <?= $this->uploader()->renderForm() ?>
            </div>
        </div>
    </div>
</div>

<!-- <script src="/js/masonry.pkgd.min.js" type="text/javascript"></script> -->


<link rel="stylesheet" href="/css/colpick.css" type="text/css"/>
<link rel="stylesheet" href="/css/ui-lightness/jquery-ui-1.10.4.custom.min.css" type="text/css"/>
<style type="text/css">
#ui-datepicker-div  .ui-widget-header {
    background: #FFFFFF  no-repeat scroll 50% 50% #F6A828;
}
#ui-datepicker-div.ui-widget-content {
    background: #FFFFFF  no-repeat scroll 50% 50% #F6A828;
}
</style>


<?php ob_start() ?>
<script type="text/javascript">
//Color Picker
if (!Modernizr.inputtypes.color) {
    $(document).ready(function (){
        var colorInput = $('#colpick');
        var colorInputValue = colorInput.val();
        if ('' != colorInputValue) {
            colorInput.css('color', '#' + colorInputValue);
            colorInput.css('background', '#' + colorInputValue);
        }
        colorInput.colpick({
            layout:'hex',
            submit:0,
            colorScheme:'dark',
            onChange:function(hsb,hex,rgb,el,bySetColor) {
                $(el).css('background','#'+hex);
                $(el).css('color','#'+hex);
                // Fill the text box just if the color was set using the picker, and not the colpickSetColor function.
                if(!bySetColor) $(el).val(hex);
            }
        }).keyup(function(){
            $(this).colpickSetColor(this.value);
        });
    });
}
</script>
<?php $conditional_colpick = ob_get_clean() ?>

<?php ob_start() ?>
<script type="text/javascript">
//End Color Picker
//Date Picker
if (!Modernizr.inputtypes.date) {
    $(document).ready(function (){
        $("#datepicker").datepicker();
    });
}
//End Color Picker
</script>
<?php $conditional_datepicker = ob_get_clean() ?>

<?php $this->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>

<?php $this->scriptalicious()->addSrc('colpick', '/js/colpick.js')
    ->addDependency('colpick', 'jQuery') ?>

<?php $this->scriptalicious()->addInline('conditional_colpick', $conditional_colpick)
    ->addDependency('conditional_colpick', 'colpick') 
    ->addDependency('conditional_colpick', 'modernizr_input') ?>

<?php $this->scriptalicious()->addInline('conditional_datepicker', $conditional_datepicker)
    ->addDependency('conditional_datepicker', 'jQuery') //of what only datepicker
    ->addDependency('conditional_datepicker', 'modernizr_input') ?>

<?php $this->scriptalicious()->addSrc('modernizr_input', '/js/modernizr.input.min.js')
    ->addDependency('modernizr_input', 'jQuery') ?>

<?php include_once $this->uploader()->getScriptPath() ?>
