<?php foreach ($dogs as $dog) : ?>
<div class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <?php $patterns = array(':dogname')?>
        <?php $replacements = array($dog['dog_name'])?>
        <h1><?= $this->patternTranslate($patterns, $replacements, "Woff!! I'm :dogname") ?></h1>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
</div>
<div class="row">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-sm-4 col-md-3 col-lg-3">
        <img src="<?= $dog['media_src']?>" alt="<?= $dog['media_alt']?>"/>
    </div>
    <div class="col-sm-6 col-md-5 col-lg-5" style="background:red;">
    <h3><?= $this->translate('Dog Info') ?></h3>
        <ul>
            <li><?= $this->translate('Weight Kg') ?>: <strong><?= $dog['dog_weightkg'] ?></strong></li>
            <li><?= $this->translate('Gender') ?>: <strong><?= $this->translate((('f' === $dog['dog_gender'])? 'Female': 'Male')) ?></strong></li>
            <li><?= $this->translate('Breed') ?>: <strong><?= $dog['dog_breed'] ?></strong></li>
            <li><?= $this->translate('Color') ?>: <strong><?= $dog['dog_color'] ?></strong></li>
            <li><?= $this->translate('Born in') ?>: <strong><?= $dog['dog_birthdate'] ?></strong></li>
        </ul>
        <?php $patterns = array(':user', ':dog') ?>
        <?php $replacements = array($dog['user_uniquename'], $dog['dog_name']) ?>
        <h3><?= $this->patternTranslate($patterns, $replacements, ":user chose :dog over any other dog because") ?></h3>
        <p><?= $dog['dog_whythisdog'] ?></p>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
</div>
<?php endforeach ?>
