<?php if (isset($messages) && !empty($messages)) : ?>
  <div class="row messages">
    <div class="col-xs-1 col-md-2 col-lg-2"></div>
    <div class="col-xs-10 col-md-8 col-lg-8">
    <?php foreach ($messages as $class => $message) : ?>
      <?= $this->message($class, $this->translate($message, 'dogtore')) ?>
    <?php endforeach ?>
    </div>
    <div class="col-xs-1 col-md-2 col-lg-2"></div>
<?php endif ?>
