<div class="row post-search-row">
<?php
$form->setAttribute('action', $this->url('dogtore_search', array(), true));
$form->setAttribute('method', 'get');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?= $this->form()->openTag($form) ?>
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
  <div class="col-xs-10 col-md-10 col-lg-10">
    <div class="input-group">
      <?= $this->formElement($form->get('t')) ?>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><?= $this->translate('Any', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('symptom') ?>" type="submit" name="c" value="<?= $this->translate('symptom', 'dogtore')?>"><?= $this->translate('Symptoms', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('cause') ?>" type="submit" name="c" value="<?= $this->translate('cause', 'dogtore')?>"><?= $this->translate('Causes', 'dogtore')?></button>
        <button class="btn btn-<?= $this->cssClass('solution') ?>" type="submit" name="c" value="<?= $this->translate('solution', 'dogtore')?>"><?php echo $this->translate('Solutions', 'dogtore')?></button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
<?= $this->form()->closeTag() ?>
</div><!-- /.row -->
