<?php $view->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>
<?php $view->scriptalicious()->addSrc('image_picker', '/js/image-picker.min.js')
    ->addDependency('image_picker', 'jQuery') ?>
<?php $view->scriptalicious()->addSrc('masonry', '/js/masonry.pkgd.min.js')
    ->addDependency('masonry', 'jQuery') ?>

<?php ob_start() ?>
<script type="text/javascript">

// Function that changes the popup hidden state
function gbiliUploaderShowUploadPopup () {
    var popupUploadForm = $('#<?= $this->popupDivId ?>')[0];
    if (-1 !== typeof popupUploadForm.className.indexOf('hidden')) {
        popupUploadForm.className = popupUploadForm.className.replace('hidden', '');
    }
}

// Function that changes the popup hidden state
function gbiliUploaderHideUploadPopup () {
    var popupUploadForm = $('#<?= $this->popupDivId ?>')[0];
    if (-1 === popupUploadForm.className.indexOf('hidden')) {
        popupUploadForm.className = popupUploadForm.className += ' hidden'; 
    }
}

function gbiliUploaderInitImagePicker() {
    $("select.image-picker").imagepicker();
    var $container = $("select.image-picker.masonry").next('ul.thumbnails');
    $container.masonry({
        itemSelector: 'li',
    });
}

function gbiliUploaderReloadImagePicker() {
    var currentImagePicker = $("ul.thumbnails");
    currentImagePicker.remove();
    gbiliUploaderInitImagePicker();
}

/*
 * Add a button to the below the image picker selector, 
 * that will trigger the popup form
 */
function gbiliUploaderInitButtonAddMedia() {
    /*
     * Create the button and add it to the selector with a show listener
     */
    var buttonShowPopup = '<div class="gbiliuploader-show-popup-button"><a class="btn btn-primary">+</a></div>';
    // TODO find a better unique css selector the element is ul class="thumbnails image-picker-selector"
    // I dont know how to select the element ul that has both classes.
    var imagePickerWellContainer = $("select.image-picker").parent().parent();
    imagePickerWellContainer.html(imagePickerWellContainer.html() + buttonShowPopup);

    // Register an onclick event on the botton
    var buttonAddMedia = $('div.gbiliuploader-show-popup-button a.btn')[0];
    if (buttonAddMedia.addEventListener) {
        buttonAddMedia.addEventListener('click', gbiliUploaderShowUploadPopup, false); 
    } else if (buttonAddMedia.attachEvent)  {
        buttonAddMedia.attachEvent('onclick', gbiliUploaderShowUploadPopup);
    }
};

/*
 * Register listeners
 * Call this every time the content of the containing div is modified
 */
function gbiliUploaderAddListenersToButtonHidePopup() {
    var hidePopupButton = $('#<?= $this->popupDivId ?> > a.gbiliuploader-hide-popup-button')[0];
    if (hidePopupButton.addEventListener) {
        hidePopupButton.addEventListener('click', gbiliUploaderHideUploadPopup, false); 
    } else if (buttonAddMedia.attachEvent)  {
        hidePopupButton.attachEvent('onclick', gbiliUploaderHideUploadPopup);
    }
}

gbiliUploaderInitButtonAddMedia();
gbiliUploaderAddListenersToButtonHidePopup();
//Important to load the image picker after the add media button
gbiliUploaderInitImagePicker();
</script>
<?php $add_button_to_image_picker = ob_get_clean()?>

<?php $view->scriptalicious()->addInline('gbiliuploader_imagepicker_with_addbutton', $add_button_to_image_picker)
    ->addDependency('gbiliuploader_imagepicker_with_addbutton', 'masonry')
    ->addDependency('gbiliuploader_imagepicker_with_addbutton', 'image_picker') ?>

<?php unset($add_button_to_image_picker) ?>
