<?php require_once __DIR__ . '/ajax.file_upload.js.phtml' ?>

<?php $view->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>
<?php $view->scriptalicious()->addSrc('imagesloaded', '/js/imagesloaded.pkgd.min.js')
    ->addDependency('imagesloaded', 'jQuery') ?>
<?php $view->scriptalicious()->addSrc('masonry', '/js/masonry.pkgd.min.js')
    ->addDependency('masonry', 'jQuery') ?>

<?php ob_start() ?>
<script type="text/javascript">
/* Filename: <?= __FILE__ ?> */
/*
 * When used alongside image_picker, gbiliuploader is presented as a popup
 */
// Function that changes the popup hidden state
function gbiliUploaderShowUploadPopup () {
    var popupUploadForm = $('#<?= $this->popupDivId ?>')[0];
    if (-1 !== typeof popupUploadForm.className.indexOf('hidden')) {
        popupUploadForm.className = popupUploadForm.className.replace('hidden', '');
    }
}

// Function that changes the popup hidden state
function gbiliUploaderHideUploadPopup () {
    var popupUploadForm = $('#<?= $this->popupDivId ?>')[0];
    if (-1 === popupUploadForm.className.indexOf('hidden')) {
        popupUploadForm.className = popupUploadForm.className += ' hidden'; 
    }
}

// Would be lazier if it were on the showPopup
function gbiliUploaderHideAndResetPopup () {
    gbiliUploaderHideUploadPopup();
    //remove alerts
    $('#<?= $this->popupDivId ?> .alert').remove();
    gbiliUploaderResetProgress();
}

/*
 * Add a button to the below the image picker selector, 
 * that will trigger the popup form
 */
function gbiliUploaderInitButtonAddMedia() {
    /*
     * Create the button and add it to the selector with a show listener
     */
    var buttonShowPopup = '<div class="gbiliuploader-show-popup-button"><a class="btn btn-primary">+</a></div>';
    // TODO find a better unique css selector the element is ul class="thumbnails image-picker-selector"
    // I dont know how to select the element ul that has both classes.
    var brickWall = $(".brick-wall > div").append(buttonShowPopup);

    gbiliUploaderSetEventListenerClickAddMediaButton();
};

function gbiliUploaderSetEventListenerClickAddMediaButton() {
    // Register an onclick event on the botton
    var buttonAddMedia = $('div.gbiliuploader-show-popup-button a.btn')[0];
    if (buttonAddMedia.addEventListener) {
        buttonAddMedia.addEventListener('click', gbiliUploaderShowUploadPopup, false); 
    } else if (buttonAddMedia.attachEvent)  {
        buttonAddMedia.attachEvent('onclick', gbiliUploaderShowUploadPopup);
    }
}

/*
 * Register listeners
 * Call this every time the content of the containing div is modified
 */
function gbiliUploaderSetEventListenerClickHidePopupButton() {
    var hidePopupButton = $('#<?= $this->popupDivId ?> > a.gbiliuploader-hide-popup-button')[0];
    if (hidePopupButton.addEventListener) {
        hidePopupButton.addEventListener('click', gbiliUploaderHideAndResetPopup, false); 
    } else if (hidePopupButton.attachEvent)  {
        hidePopupButton.attachEvent('onclick', gbiliUploaderHideAndResetPopup);
    }
}

/*
 * Reload Image picker with new image
 *
 * 1.Append the uploaded image to the image select
 * 2.Reload image-picker on select so that the new image
 * is available for select
 */
function gbiliUploaderAddImagesToMasonizeableWall(response) {
    var callbackReturn = response.callbackReturn;
    var $masonizeableList = $('.brick-wall div ul[class*="please_masonize_"]');
    for( key in  callbackReturn) {
        listItem = document.createElement('li');
        console.log(listItem);
        listItem.innerHTML = '<a href=""><img class="img-responsive" src="' + callbackReturn[key].mediaSrc + '"></a>'
             + '<div class="caption">'
             + '<h5></h5>'
             + '</div>';
        $masonizeableList.prepend(listItem);
        $masonizeableList.masonry('prepended', listItem);
    }
    $masonizeableList.imagesLoaded(function () {
        $masonizeableList.masonry('layout');
    });
}

if (!gbiliUploaderUploadSuccessCallback) {
    var gbiliUploaderUploadSuccessCallback;
}
gbiliUploaderUploadSuccessCallback = function (response) {
    gbiliUploaderUploadSuccess(response);
    gbiliUploaderAddImagesToMasonizeableWall(response);
    gbiliUploaderSetEventListenerClickHidePopupButton();
};

if (!gbiliUploaderUploadFailCallback) {
    var gbiliUploaderUploadFailCallback;
}
gbiliUploaderUploadFailCallback = function (response) {
    gbiliUploaderUploadFail(response);
    gbiliUploaderSetEventListenerClickHidePopupButton();
};

if (!gbiliUploaderUploadPartialSuccessCallback) {
    var gbiliUploaderUploadPartialSuccessCallback;
}
gbiliUploaderUploadPartialSuccessCallback = function (response) {
    gbiliUploaderUploadPartialSuccess(response);
    gbiliUploaderAddImagesToMasonizeableWall(response);
    gbiliUploaderSetEventListenerClickHidePopupButton();
};

gbiliUploaderInitButtonAddMedia();
gbiliUploaderSetEventListenerClickHidePopupButton();
</script>
<?php $add_button_to_image_picker = ob_get_clean()?>

<?php $view->scriptalicious()->addInline('gbiliuploader_ajax_media_upload', $add_button_to_image_picker)
    ->addDependency('gbiliuploader_ajax_media_upload', 'masonry')
    ->addDependency('gbiliuploader_ajax_media_upload', 'imagesloaded')
    ->addDependency('gbiliuploader_ajax_media_upload', 'gbiliuploader_ajax_file_upload')?>

<?php unset($add_button_to_image_picker) ?>
