<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}
$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$title = ucfirst($this->translate($action)) . ' ' . ucfirst($this->translate($controller));
$route = array(
    'lang' => $this->lang(),
    'action' => $action
);
$form->setAttribute('action', $this->url(null ,$route));
$this->headTitle($title);
$form->prepare();
?>
<?php if (isset($messages) && !empty($messages)) : ?>
    <?php $messages['helper_name'] = 'fileUploadMessage'?>
    <?php $this->notify($messages) ?>
<?php endif ?>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>
<div class="row">
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
    <?php echo $this->form()->openTag($form)?>
        <?= $this->formFileUploadProgress(); ?>
        <?php foreach ($form->getElements() as $element) : ?>
            <div class="form-group">
                <?php echo ((null !== $element->getLabel())? $this->translate($this->formLabel($element), 'blog') : '') ?>
                <?php echo $this->formElement($element) ?>
            </div>
        <?php endforeach ?>
    <?php echo $this->form()->closeTag() ?>
    </div>
    <div class="col-sm-0 col-md-2 col-lg-2"></div>
</div>

<?php include __DIR__ . '/'.  $this->ajaxFileUpload()->getScriptFilename() ?>
