<?php $this->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>

<?php $this->scriptalicious()->addSrc('image_picker', '/js/image-picker.min.js')
    ->addDependency('image_picker', 'jQuery') ?>

<?php ob_start() ?>
<script type="text/javascript">
//Image Picker
$("select.image-picker").imagepicker();

//Trying to masonize image picker
//var container = $(".image_picker_selector").next('ul.thumbnails');
//container.imagesLoaded(function (){
//    container.masonry({
//    itemSelector : "li",
//    });
//});
// End Image Picker
</script>
<?php $init_image_picker = ob_get_clean() ?>

<?php $this->scriptalicious()->addInline('init_image_picker', $init_image_picker)
    ->addDependency('init_image_picker', 'image_picker') ?>

<?php unset($init_image_picker) ?>
