<?php $view->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>

<?php $view->scriptalicious()->addSrc('image_picker', '/js/image-picker.min.js')
    ->addDependency('image_picker', 'jQuery') ?>

<?php ob_start() ?>
<script type="text/javascript">
// Standard image picker
$("select.image-picker").imagepicker();
</script>
<?php $init_image_picker = ob_get_clean() ?>

<?php $view->scriptalicious()->addInline('init_image_picker', $init_image_picker)
    ->addDependency('init_image_picker', 'image_picker') ?>

<?php unset($init_image_picker) ?>
