<?php
$title = 'Posts';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?php echo $this->url('blog', array(
            'controller' => 'post', 
            'action'=>'create',
        ));?>"><?php echo $this->translate('Add New Post', 'blog')?></a></p>
    </div>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th><?php echo $this->translate('Id', 'blog')?></th>
        <th><?php echo $this->translate('Title', 'blog')?></th>
        <th><?php echo $this->translate('Slug', 'blog')?></th>
        <th><?php echo $this->translate('Category', 'blog')?></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($posts as $post) : ?>
	    <tr>
	        <td><?php echo $this->escapeHtml($post->getId());?></td>
	        <td><?php echo $this->escapeHtml($post->getData()->getTitle());?></td>
	        <td><?php echo $this->escapeHtml($post->getSlug());?></td>
	        <td><?php echo $this->escapeHtml($post->getCategory()->getName());?></td>
	        <td>
                <a href="<?php echo $this->url('blog', array(
                    'controller' => 'post', 
                    'action' => 'edit', 
                    'id' => $post->getId(),
                )); ?>"><?php echo $this->translate('Edit', 'blog')?></a>

	        </td>
	        <td>
                <a href="<?php echo $this->url('blog', array(
                    'controller' => 'post', 
                    'action' => 'delete',
                    'id' => $post->getId()
                )); ?>" onclick="return confirm('Are you sure?')"><?php echo $this->translate('Delete', 'blog')?></a>
	        </td>
	    </tr>
    <?php endforeach; ?>
    <?php if (empty($posts)) : ?>
	    <tr>
            <td><?php echo $this->translate('You have not written any posts for the moment...', 'blog')?></td>
	    </tr>
    <?php endif ?>
</table>
