<?php
$title = $this->translate('Media Library');
$this->headTitle($title);
$this->notify(((isset($messages))? $messages : array()));
?>
<header class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h3><?= $this->escapeHtml($title); ?></h3>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-default" href="<?= $this->url(null, array('action'=>'create'), true);?>" title="<?= $this->translate('Media from previously uploaded image') ?>"><?= $this->translate('Create from Existing') ?></a></p>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?= $this->url(null, array('action'=>'upload'), true);?>"><?= $this->translate('Upload media') ?></a></p>
    </div>
</header>

<?php $this->nonce()->setRouteName('blog_media_delete_route') ?>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
<ul class="image-library">
    <?php foreach($medias as $media) : ?>
    <li>
    <a href="<?= $this->url('blog_media_view', array('slug' => $media->getSlug()), true) ?>"><img class="img-responsive" src="<?= $this->escapeHtml($media->getFile()->getSrc());?>"></a>
      <div class="caption">
        <h5><?= $this->escapeHtml($media->getSlug());?></h5>
        <p>
            <?php if (!$media->getPosts()->isEmpty()) : ?>
                <?php $linkedPosts = array();
                    foreach ($media->getPosts() as $post) :
                        $unlinkPostActionHref = $this->url(null, 
                            array(
                                'action' => 'unlink', 
                                'id' => $media->getId(),
                                'fourthparam' => $post->getId(),
                            ),
                            true
                        );
                        $unlinkablePosts[] = $post->getTitle() . ':<a href="' . $unlinkPostActionHref . '">' . $this->translate('unlink') .'</a>';
                    endforeach;
                    echo implode(', ', $unlinkablePosts);?>
            <?php endif ?>
            <a class="btn btn-default btn-xs" role="button"href="<?= $this->url(null, array(
                'lang' => $this->lang(), 
                'action' => 'link', 
                'id' => $media->getId(),
            )); ?>"><?= $this->translate('Link to') ?></a>
            <a class="btn btn-primary btn-xs" role="button" href="<?= $this->url(null, array(
                'lang' => $this->lang(), 
                'action' => 'edit', 
                'id' => $media->getId(),
            )); ?>"><?= $this->translate('Edit') ?></a>
            <a class="btn btn-danger btn-xs" role="button" href="<?= $this->url($this->nonce()->getRouteName(), array(
                'lang' => $this->lang(), 
                'id' => $media->getId(),
                'nonce' => $this->nonce()->getHash($media->getId()),
            )); ?>" onclick="return confirm('<?= $this->translate('Are you sure?') ?>')"><?= $this->translate('Delete') ?></a>
        </p>
     </div><!-- end caption -->
   </li><!-- end thumbnail -->
<?php endforeach ?>
        </ul><!--masonize -->
    </div><!-- end col -->
 </div><!-- end row -->
<?php if (empty($medias)) : ?>
    <p><?= $this->translate('No medias have been uploaded') ?></p>
<?php endif ?>

<?php ob_start() ?>
<?php //TODO make this masonry work ?>
<script type="text/javascript">
$('ul.image-library').masonry({
    columnWidth: 200,
    itemSelector: 'li',
});
</script>
<?php $initMason = ob_get_clean() ?>
<?php $this->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>
<?php $this->scriptalicious()->addSrc('masonry', '/js/masonry.pkgd.min.js')
    ->addDependency('masonry', 'jQuery') ?>
<?php $this->scriptalicious()->addInline('init_image_library_mason', $initMason)
    ->addDependency('init_image_library_mason', 'masonry')
    ->addDependency('init_image_library_mason', 'jQuery');
