<?php
$title = $this->translate('Media Library');
$this->headTitle($title);
$this->notify(((isset($messages))? $messages : array()));
?>
<header class="row">
    <div class="col-sm-4 col-md-4 col-4">
        <h3><?= $this->escapeHtml($title); ?></h3>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-default" href="<?= $this->url(null, array('action'=>'create'), true);?>" title="<?= $this->translate('Media from previously uploaded image') ?>"><?= $this->translate('Create from Existing') ?></a></p>
    </div>
    <div class="col-sm-4 col-md-4 col-4">
        <p><a class="btn btn-success" href="<?= $this->url(null, array('action'=>'upload'), true);?>"><?= $this->translate('Upload media') ?></a></p>
    </div>
</header>
<?php $count = count($medias) ?>
<?php $itemsPerRow = 4 ?>
<?php $excess = $count % $itemsPerRow ?>
<?php $rows = ($count - $excess) / $itemsPerRow ?>
<?php $isRowOpened = false ?>
<?php $i = 1 ?>

<?php $this->nonce()->setRouteName('blog_media_delete_route') ?>

    <?php foreach($medias as $media) : ?>
<?php if (1 === $i || 0 === ($i % $itemsPerRow)) : ?> 
    <div class="row">
    <?php $isRowOpened = true?>
<?php endif ?>
<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="thumbnail">
    <a href="<?= $this->url('blog_media_view', array('slug' => $media->getSlug()), true) ?>"><img class="img-responsive" src="<?= $this->escapeHtml($media->getFile()->getSrc());?>">
     </a>
      <div class="caption">
        <h5><?= $this->escapeHtml($media->getSlug());?></h5>
        <p>
            <?php if (!$media->getPosts()->isEmpty()) : ?>
                <?php $linkedPosts = array();
                    foreach ($media->getPosts() as $post) :
                        $unlinkPostActionHref = $this->url(null, 
                            array(
                                'action' => 'unlink', 
                                'id' => $media->getId(),
                                'fourthparam' => $post->getId(),
                            ),
                            true
                        );
                        $unlinkablePosts[] = $post->getTitle() . ':<a href="' . $unlinkPostActionHref . '">' . $this->translate('unlink') .'</a>';
                    endforeach;
                    echo implode(', ', $unlinkablePosts);?>
            <?php endif ?>
            <a class="btn btn-default btn-xs" role="button"href="<?= $this->url(null, array(
                'lang' => $this->lang(), 
                'action' => 'link', 
                'id' => $media->getId(),
            )); ?>"><?= $this->translate('Link to') ?></a>
            <a class="btn btn-primary btn-xs" role="button" href="<?= $this->url(null, array(
                'lang' => $this->lang(), 
                'action' => 'edit', 
                'id' => $media->getId(),
            )); ?>"><?= $this->translate('Edit') ?></a>
            <a class="btn btn-danger btn-xs" role="button" href="<?= $this->url($this->nonce()->getRouteName(), array(
                'lang' => $this->lang(), 
                'id' => $media->getId(),
                'nonce' => $this->nonce()->getHash($media->getId()),
            )); ?>" onclick="return confirm('<?= $this->translate('Are you sure?') ?>')"><?= $this->translate('Delete') ?></a>
        </p>
     </div><!-- end caption -->
   </div><!-- end thumbnail -->
</div><!-- end col -->
    <?php $i++ ?>
    <?php if (0 === ($i % $itemsPerRow)) : ?> 
             </div><!-- end row -->
        <?php $isRowOpened = false?>
    <?php endif ?>
<?php endforeach ?>
<?php if (true === $isRowOpened) : ?>
             </div><!-- end row -->
<?php endif ?>
<?php if (empty($medias)) : ?>
    <p><?= $this->translate('No medias have been uploaded') ?></p>
<?php endif ?>
