<div class="row">
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
  <div class="col-xs-10 col-md-10 col-lg-10">
    <div class="input-group">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
</div><!-- /.row -->
<?php foreach ($this->posts as $post) : ?>
<div class="row">
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
  <div class="col-xs-10 col-md-10 col-lg-10">
    <div class="thumbnail">
    <img src="" alt="Thumb <?php echo $post->getCategory() ?>">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p><?php echo $post->getContent() ?></p>
        <p>
            <a href="editor/edit/<?php echo $post->getId() ?>"></a>
        </p>
      </div>
    </div>
  </div>
  <div class="col-xs-1 col-md-1 col-lg-1"></div>
</div>
<?php endforeach ?>
